#!/bin/bash +xe

all:
  npm run dev -- --experimental-https

b:
  npm run build

c:
  npm run check

l:
  npm run lint

br:
  $BROWSER --allow-insecure-localhost https://localhost:3000 \
    --ignore-certificate-errors

wasm:
  pushd veterinary-clinic-backend
    mk wasm
  popd
  cp veterinary-clinic-backend/out/domain.wasm public/domain.wasm

wasm-exec:
  cp $(tinygo env TINYGOROOT)/targets/wasm_exec.js public/wasm_exec.js
